<a href="https://colab.research.google.com/github/chirantan2003/first-ml-project/blob/main/ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import numpy.matlib

In [2]:
def warmUpExercise():
  a=np.identity(5)
  print(a)



In [3]:
print("THIS IS WARMUP EXERCISE")
warmUpExercise()

THIS IS WARMUP EXERCISE
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Part 2 Begins:

In [5]:
print("Plotting Data")
df = pd.read_table("/content/ex1data1.txt", header = None ,delimiter=",", names=["X", "y"])
print(df)


Plotting Data
          X         y
0    6.1101  17.59200
1    5.5277   9.13020
2    8.5186  13.66200
3    7.0032  11.85400
4    5.8598   6.82330
..      ...       ...
92   5.8707   7.20290
93   5.3054   1.98690
94   8.2934   0.14454
95  13.3940   9.05510
96   5.4369   0.61705

[97 rows x 2 columns]


In [6]:
def plotData(x,y):
  df.plot.scatter(x="X" , y="y", s = 50, marker="x", color="red")
  plt.xlabel("population")
  plt.ylabel("profit")

plotData("X","y")

Part 3 Begins

In [49]:
A = np.matrix(df)
X = np.r_[ [np.zeros(2)],A ]
X = np.c_[ np.ones(98), X ]
print(X)
y = X[:,2]
theta = np.matlib.zeros((2,1))

iterations = 1500
alpha = 0.01




[[ 1.       0.       0.     ]
 [ 1.       6.1101  17.592  ]
 [ 1.       5.5277   9.1302 ]
 [ 1.       8.5186  13.662  ]
 [ 1.       7.0032  11.854  ]
 [ 1.       5.8598   6.8233 ]
 [ 1.       8.3829  11.886  ]
 [ 1.       7.4764   4.3483 ]
 [ 1.       8.5781  12.     ]
 [ 1.       6.4862   6.5987 ]
 [ 1.       5.0546   3.8166 ]
 [ 1.       5.7107   3.2522 ]
 [ 1.      14.164   15.505  ]
 [ 1.       5.734    3.1551 ]
 [ 1.       8.4084   7.2258 ]
 [ 1.       5.6407   0.71618]
 [ 1.       5.3794   3.5129 ]
 [ 1.       6.3654   5.3048 ]
 [ 1.       5.1301   0.56077]
 [ 1.       6.4296   3.6518 ]
 [ 1.       7.0708   5.3893 ]
 [ 1.       6.1891   3.1386 ]
 [ 1.      20.27    21.767  ]
 [ 1.       5.4901   4.263  ]
 [ 1.       6.3261   5.1875 ]
 [ 1.       5.5649   3.0825 ]
 [ 1.      18.945   22.638  ]
 [ 1.      12.828   13.501  ]
 [ 1.      10.957    7.0467 ]
 [ 1.      13.176   14.692  ]
 [ 1.      22.203   24.147  ]
 [ 1.       5.2524  -1.22   ]
 [ 1.       6.5894   5.9966 ]
 [ 1.     

In [82]:
def computeCost(X, y, theta):
  J = 0
  initialTheta=theta
  # print(theta, "this is theta")
  theta = np.matlib.repmat(theta, 49, 1)
  # print(theta)
  thetaTranspose = np.transpose(theta)
  # print(thetaTranspose, "this is theta")
  # print(X, "this is x")
  # print(y, "this is  y")
  multip = np.matmul(thetaTranspose, X)
  # print(multip, "this is multip")
  asd = sum(np.square((multip - y)))/(97*2)
  computedCost = asd.item(1)
  return computedCost
  


In [83]:
J = computeCost(X,y,theta)
print("With theta = [0 ; 0] computed cost = " '%.2f'%J)
print("Expected cost value approx 32.07")

With theta = [0 ; 0] computed cost = 32.07
Expected cost value approx 32.07


In [84]:
J = computeCost(X,y, np.matrix('0.1 ; 0.1'))
print("With theta = [-1 ; 2] computed cost = " '%.2f'%J)
print("Expected cost value approx 54.24")

With theta = [-1 ; 2] computed cost = 2734.56
Expected cost value approx 54.24
